title: Project
frontmatter: project
cases:
  - title: settings output_stderr
    raw:
      settings:
        output_stderr: remove
        stdout_output: warn
    errors: 0
    normalized:
      settings:
        output_stderr: remove
        output_stdout: warn
  - title: settings output_stderr bad value
    raw:
      settings:
        output_stderr: ok
        output_stdout: ok
    errors: 2
    normalized: {}
  - title: settings unknown value
    raw:
      settings:
        what: ok
    warnings: 1
    normalized: {}
