# ReadTheDocs configuration structure
# This is *only meant for PR previews*.
# Our live documentation is hosted via a Vercel site.
# ref for docs: https://mystmd.org/guide/contribute-docs
# ref for RTD config: https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
conda:
  environment: docs/environment.yml
build:
  os: ubuntu-lts-latest
  tools:
    nodejs: "20"
    python: "3.11"
  commands:
    # Install dependencies and build MyST so we're using `main`
    - npm install
    - npm run build
    - npm run --workspace packages/mystmd link
    - myst --version
    - cd docs && BASE_URL=${READTHEDOCS_CANONICAL_URL} myst build --html --execute
    # Move MyST outputs to the ReadTheDocs output folder for inclusion
    # TODO: Switch to rsync
    # https://github.com/readthedocs/readthedocs.org/issues/11219
#    - /usr/bin/rsync -a --mkpath docs/_build/ $READTHEDOCS_OUTPUT/
    - mkdir -p $READTHEDOCS_OUTPUT
    - cp -a docs/_build/* $READTHEDOCS_OUTPUT/
    # Copy robots.txt to avoid search indexing
    - cp .github/robots.txt $READTHEDOCS_OUTPUT/robots.txt
