[build]
  command = """
  pip install -r docs/requirements.txt;
  npm run build;
  npm run --workspace packages/mystmd link;
  cd docs;
  myst build --html --execute
  """
  publish = "/docs/_build/html/"