name: MyST Install Action
description: Checkout MyST and install Node, MyST, and other dependencies
inputs:
  node:
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: recursive
    - name: Install libxml
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-utils
    - name: Setup Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node }}
        cache: 'npm'
    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: '.github/requirements/requirements-execute.txt'
    - name: Install execution requirements for ipykernel and jupyter-server
      run: python -m pip install -r .github/requirements/requirements-execute.txt
    - name: Install node deps
      run: npm install
    - name: Run build
      run: npm run build
